name: Build Main_MiSTer
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build MiSTer Binary
        uses: the-mister-devel-project/mister-build-action@v1
        with:
          target: 'Main_MiSTer'

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer
          path: MiSTer
